#!/usr/bin/env python3
"""Emit paper_updates.tex: drop-in replacements for the NeurIPS draft's mechanism
section, generated straight from the result JSON so no number is hand-copied."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "relabel_analysis"
DEST = Path(__file__).resolve().parent / "paper_updates.tex"

ORDER = ["Qwen3-14B", "Mistral-7B-Instruct-v0.3", "c4ai-command-r7b-12-2024",
         "gemma-3-27b-it", "Meta-Llama-3.1-70B-Instruct"]
ROW = {"Qwen3-14B": "Qwen3-14B", "Mistral-7B-Instruct-v0.3": "Mistral-7B",
       "c4ai-command-r7b-12-2024": "Command-R-7B", "gemma-3-27b-it": "Gemma-3-27B",
       "Meta-Llama-3.1-70B-Instruct": "Llama-3.1-70B"}
LAYER = {"Qwen3-14B": "33/40", "Mistral-7B-Instruct-v0.3": "26/32",
         "c4ai-command-r7b-12-2024": "26/32", "gemma-3-27b-it": "51/62",
         "Meta-Llama-3.1-70B-Instruct": "67/80"}
# unchanged columns, carried over from the current draft (not rerun; see notes)
SUPPRESSION = {"Qwen3-14B": "$66.8,\\ t{=}5.6$", "Mistral-7B-Instruct-v0.3": "$1.4,\\ t{=}5.1$",
               "c4ai-command-r7b-12-2024": "$26.4,\\ t{=}9.7$",
               "gemma-3-27b-it": "$2902,\\ t{=}4.0$",
               "Meta-Llama-3.1-70B-Instruct": "$0.2,\\ t{=}0.4$"}
PATCHING = {"Qwen3-14B": "18", "Mistral-7B-Instruct-v0.3": "24",
            "c4ai-command-r7b-12-2024": "62", "gemma-3-27b-it": "46",
            "Meta-Llama-3.1-70B-Instruct": "40"}


def g(m):
    return json.loads((OUT / f"gpu_{m}.json").read_text())


def s_(m):
    return json.loads((OUT / f"steer_{m}.json").read_text())


def s(m):
    return s_(m)


def a(m):
    return json.loads((OUT / f"ablation_action_{m}.json").read_text())


def audit():
    return json.loads((OUT / "degeneracy_audit.json").read_text())


def clean_addition(m):
    """Addition at 4x the projection gap drives every model into degenerate output,
    so that column measures breakage rather than refusal. Report instead the benign
    refusal rate at the largest steering coefficient whose output is still clean --
    that intervention IS activation addition, just at a magnitude the model survives."""
    A, st = audit(), s_(m)["steering"]
    best = None
    for i, c in enumerate(st["grid"]):
        row = A.get(f"{m}|steer|{c}")
        if row and row["degenerate"] < 0.05:
            best = (c, st["benign_refuse_new"][0], st["benign_refuse_new"][i])
    return best


def pct(x):
    return f"{round(100 * x):d}\\%"


L = []
w = L.append

w("% ============================================================================")
w("% paper_updates.tex --- drop-in replacements for the mechanism section.")
w("% Generated by make_paper_updates.py from relabel_analysis/*.json.")
w("%")
w("% The TABLES below are ready to paste. The WRITING OUTLINES after them are")
w("% commented-out notes on what each paragraph must cover and which numbers to")
w("% cite -- deliberately not drafted prose, so the text stays in the authors' voice.")
w("%")
w("% Every number is recomputed on the corrected labels and the corrected")
w("% tool-safety scorer. Two columns of Table 2 are NOT rerun and are carried over")
w("% verbatim from the current draft: Suppression and Patching. Both are")
w("% classifier-independent, so the relabel cannot move them, but see NOTES at the")
w("% bottom for why re-verifying them is still worth an hour of GPU.")
w("% ============================================================================")
w("")
w("% ---------------------------------------------------------------------------")
w("% 1. REPLACEMENT FOR Table~\\ref{tab:mech}")
w("% ---------------------------------------------------------------------------")
w("\\begin{table}[t]")
w("\\centering")
w("\\setlength{\\tabcolsep}{4pt}")
w("\\caption{The refusal direction predicts tool-call safety across all five families (bf16).")
w("Suppression is the paired drop in refusal activation from no-tool to tool-normal, reported as")
w("mean $\\Delta$ and $t$-statistic ($n{=}96$); $\\Delta$ is in each model's own activation units, so")
w("magnitudes are not comparable across rows. Ablation and addition give refusal rates before and")
w("after the intervention, on harmful and benign prompts respectively, scored by the same")
w("three-way classifier used for Table~\\ref{tab:headline-divergence} ($n{=}240$ per condition).")
w("Addition at $4\\times$ the projection gap drives every model into degenerate output, so that")
w("coefficient measures breakage rather than refusal; the addition column instead reports the")
w("largest steering coefficient whose output remains fluent. Gemma's ablation is likewise")
w("degenerate and is not reported. See the degeneracy audit for per-cell rates.")
w("AUC is the area under the ROC of low refusal activation predicting an unsafe call; patching is")
w("the fraction of unsafe calls that revert to safe when the projection is restored to its matched")
w("no-tool level. The direction remains a strong predictor in every model, but ablation no longer")
w("reduces refusal uniformly: it reverses in Qwen and Gemma (see text).}")
w("\\label{tab:mech}")
w("  \\begin{tabular}{lccccc}")
w("\\toprule")
w("Model & Layer & Suppression ($\\Delta$, $t$) & Ablation & Addition & AUC\\,/\\,Patching \\\\")
w("\\midrule")
for m in ORDER:
    st, gp = s(m), g(m)
    A = audit()
    abl_deg = A[f"{m}|ablation_ablated"]["degenerate"]
    if abl_deg >= 0.5:
        abl = r"\emph{degenerate}"
    else:
        abl = f"${pct(st['ablation_base']['new'])}\\!\\to\\!{pct(st['ablation_ablated']['new'])}$"
    ca = clean_addition(m)
    add = (f"${pct(ca[1])}\\!\\to\\!{pct(ca[2])}$ ($c{{=}}{ca[0]}$)" if ca else r"\emph{n/a}")
    auc = gp["auc_unsafe_fixed"]["auc"]
    w(f"{ROW[m]:<14} & {LAYER[m]} & {SUPPRESSION[m]}  & {abl} & {add} "
      f"& ${auc:.3f}$\\,/\\,${PATCHING[m]}\\%$ \\\\")
w("\\bottomrule")
w("\\end{tabular}")
w("\\end{table}")
w("")

w("% ---------------------------------------------------------------------------")
w("% 2. NEW TABLE: direction cosines (the Section 3.6 robustness check)")
w("% ---------------------------------------------------------------------------")
w("\\begin{table}[t]")
w("\\centering")
w("\\caption{Alignment between the three directions, at each model's operating layer.")
w("$\\hat{r}_{\\text{text}}$ is the request-type direction (harmful vs.\\ benign, no-tool);")
w("$\\hat{r}_{\\text{tool}}$ is the same contrast extracted under tool prompts;")
w("$\\hat{r}_{\\text{behav}}$ is the behaviour-defined direction (refused vs.\\ complied harmful).")
w("The final column recomputes $\\hat{r}_{\\text{behav}}$ under the previous labels: the two agree")
w("at $0.96$--$0.98$ everywhere, so this check does not depend on the relabel.}")
w("\\label{tab:cosine}")
w("  \\begin{tabular}{lcccc}")
w("\\toprule")
w("Model & Layer & $\\cos(\\hat{r}_{\\text{text}},\\hat{r}_{\\text{behav}})$ "
  "& $\\cos(\\hat{r}_{\\text{text}},\\hat{r}_{\\text{tool}})$ "
  "& $\\hat{r}_{\\text{behav}}$ old vs.\\ new \\\\")
w("\\midrule")
for m in ORDER:
    d = g(m)
    w(f"{ROW[m]:<14} & {LAYER[m]} & ${d['cos_rtext_rbehav_strict']:.3f}$ "
      f"& ${d['cos_rtext_rtool']:.3f}$ & ${d['cos_rbehav_old_new']:.3f}$ \\\\")
w("\\bottomrule")
w("\\end{tabular}")
w("\\end{table}")
w("")

w("% ---------------------------------------------------------------------------")
w("% 3. NEW TABLE: does ablation change the action, or only the wording?")
w("% ---------------------------------------------------------------------------")
w("\\begin{table}[t]")
w("\\centering")
w("\\caption{Ablation's effect on behaviour rather than wording, on harmful tool-enabled")
w("prompts ($n{=}200$, paired). Unsafe-tool-call scoring is a predicate over the parsed calls, so")
w("no refusal classifier enters this measurement. ``Calls'' is the share of prompts on which the")
w("model emits any tool call; ``Unsafe\\,$\\mid$\\,calls'' is the unsafe rate among those. The")
w("headline rate moves in both directions across families, but the conditional rate is near-flat")
w("everywhere: ablation changes how often a model acts, not how safely it acts once it does.}")
w("\\label{tab:ablation-action}")
w("  \\begin{tabular}{lccccc}")
w("\\toprule")
w("Model & Unsafe (base $\\to$ abl.) & $\\Delta$ (95\\% CI) & Calls (base $\\to$ abl.) "
  "& Unsafe\\,$\\mid$\\,calls \\\\")
w("\\midrule")
for m in ORDER:
    d = a(m)
    lo, hi = d["delta_ci_paired"]
    cond = "n/a" if d.get("unsafe_given_called_abl") is None \
        else f"${d['unsafe_given_called_base']:.2f}\\!\\to\\!{d['unsafe_given_called_abl']:.2f}$"
    w(f"{ROW[m]:<14} & ${d['unsafe_baseline']:.3f}\\!\\to\\!{d['unsafe_ablated']:.3f}$ "
      f"& ${d['delta_unsafe']:+.3f}$ $({lo:+.2f},{hi:+.2f})$ "
      f"& ${d['called_tool_baseline']:.3f}\\!\\to\\!{d['called_tool_ablated']:.3f}$ & {cond} \\\\")
w("\\bottomrule")
w("\\end{tabular}")
w("\\end{table}")
w("")

# ---------------------------------------------------------------------------
# 4. Patching rerun, with the flip decomposed into safe-call vs no-call
# ---------------------------------------------------------------------------
PUBLISHED_PATCH = {"Qwen3-14B": 18, "Mistral-7B-Instruct-v0.3": 24, "c4ai-command-r7b-12-2024": 62,
                   "gemma-3-27b-it": 46, "Meta-Llama-3.1-70B-Instruct": 40}


def patch(m):
    p = OUT / f"patching_{m}.json"
    return json.loads(p.read_text()) if p.exists() else None


w("% ---------------------------------------------------------------------------")
w("% 4. REPLACEMENT for the patching row of Table~\\ref{tab:mech}, as its own table.")
w("%    The draft reports one number per model (unsafe -> safe after patching the")
w("%    refusal projection to its matched no-tool value). That number cannot tell a")
w("%    safer call from no call at all, so it is split here. Predicate-scored, no")
w("%    classifier; every generation saved; degeneracy screened.")
w("% ---------------------------------------------------------------------------")
w("\\begin{table}[t]")
w("\\centering")
w("\\caption{Activation patching on harmful tool-enabled prompts: the refusal projection at the")
w("operating layer is overwritten with its value on the matched no-tool prompt, and unsafe calls")
w("that revert are counted ($n{=}300$ baseline prompts per model; flips are over the unsafe")
w("subset, with bootstrap 95\\% CIs). ``via safe call'' means the patched model still called a tool")
w("and the call scored safe; ``via no call'' means it emitted no tool call. Unsafe\\,$\\mid$\\,call")
w("is the unsafe rate among calls the patched model still makes. Patching moves models from")
w("acting to refusing in text; it does not make the calls they still make safer.}")
w("\\label{tab:patching}")
w("  \\begin{tabular}{lcccccc}")
w("\\toprule")
w("Model & Unsafe base & Flip (draft) & Flip (rerun, 95\\% CI) & via safe call & via no call "
  "& Unsafe\\,$\\mid$\\,call \\\\")
w("\\midrule")
for m in ORDER:
    r = patch(m)
    if r is None:
        w(f"{ROW[m]:<14} & -- & {PUBLISHED_PATCH[m]}\\% & \\multicolumn{{4}}{{c}}{{not rerun}} \\\\")
        continue
    lo, hi = r["flip_rate_all_ci"]
    dag = "$^\\dagger$" if r.get("quantized_4bit") else ""
    ugc = "--" if r["unsafe_given_call_patched"] is None else pct(r["unsafe_given_call_patched"])
    w(f"{ROW[m]:<14}{dag} & {pct(r['baseline_unsafe_rate'])} & {PUBLISHED_PATCH[m]}\\% "
      f"& {pct(r['flip_rate_all'])} ({round(100 * lo)}, {round(100 * hi)}) "
      f"& {pct(r['flip_via_safe_call'])} & {pct(r['flip_via_no_call'])} & {ugc} \\\\")
w("\\bottomrule")
w("\\end{tabular}")
if any((patch(m) or {}).get("quantized_4bit") for m in ORDER):
    w("\\\\[2pt] {\\footnotesize $^\\dagger$ run with 4-bit NF4 weights (bf16 compute) on an 80\\,GB card;")
    w("the direction was extracted from the bf16 model.}")
w("\\end{table}")
w("")

# ---------------------------------------------------------------------------
# 5. Steering with the call rate explicit on both sides
# ---------------------------------------------------------------------------
SC = json.loads((OUT / "steering_calls.json").read_text()) if (OUT / "steering_calls.json").exists() else {}
w("% ---------------------------------------------------------------------------")
w("% 5. REPLACEMENT for the steering figure/paragraph. Any-call is reported on both")
w("%    sides because 'unsafe -> 0' by way of 'no calls' is not safer calling, and")
w("%    text-judged over-refusal misses a model that answers a benign tool task in")
w("%    prose without doing it. Rows whose outputs are mostly degenerate (v2 rule)")
w("%    are kept but marked; their refusal numbers should not be quoted.")
w("% ---------------------------------------------------------------------------")
w("\\begin{table}[t]")
w("\\centering")
w("\\caption{Steering along $r_\\text{text}$ in tool mode, by coefficient. Harmful side: share")
w("of prompts with any tool call, unsafe-call rate, and the unsafe rate among calls made. Benign")
w("side: share with any tool call (task completion) and judged over-refusal. Deg.\\ is the share")
w("of degenerate outputs (repetition/non-linguistic); rows above 25\\% are marked $\\ddagger$ and")
w("their rates are artefacts. Unsafe\\,$\\mid$\\,call never falls: steering removes unsafe calls")
w("by removing calls, on both sides.}")
w("\\label{tab:steering-calls}")
w("  \\begin{tabular}{lr|ccc|cc|c}")
w("\\toprule")
w(" & & \\multicolumn{3}{c|}{Harmful} & \\multicolumn{2}{c|}{Benign} & \\\\")
w("Model & $c$ & Any call & Unsafe & Unsafe\\,$\\mid$\\,call & Any call & Over-refusal & Deg. \\\\")
w("\\midrule")
for m in ORDER:
    for i, r in enumerate(SC.get(m, {}).get("rows", [])):
        deg = max(r["h_degen_v2"], r["b_degen_v2"])
        mark = "$^\\ddagger$" if deg >= 0.25 else ""
        ugc = "--" if r["h_unsafe_given_call"] is None else f"{r['h_unsafe_given_call']:.2f}"
        name = ROW[m] if i == 0 else ""
        w(f"{name:<14} & {r['coef']}{mark} & {r['h_any_call']:.2f} & {r['h_unsafe']:.2f} & {ugc} "
          f"& {r['b_any_call']:.2f} & {r['b_over_refusal']:.2f} & {pct(deg)} \\\\")
    w("\\midrule")
L.pop()  # drop the trailing midrule
w("\\bottomrule")
w("\\end{tabular}")
w("\\end{table}")
w("")

# ---------------------------------------------------------------------------
# 6. Direction admissibility (KL guardrail) and ablation controls
# ---------------------------------------------------------------------------


def ctrl(m):
    p = OUT / f"controls_{m}.json"
    return json.loads(p.read_text()) if p.exists() else None


def ctrl_j(m):
    p = OUT / f"controls_{m}_judged.json"
    return json.loads(p.read_text()).get("conditions", {}) if p.exists() else {}


def cj(m, key):
    r = ctrl_j(m).get(key)
    if r is None:
        return "--"
    s = f"{r['refuse_clean']:.2f}" if r["refuse_clean"] is not None else "--"
    return s + (f"$^\\ddagger$" if r["degenerate_v2"] >= 0.25 else "")


w("% ---------------------------------------------------------------------------")
w("% 6. NEW TABLE: is the direction admissible, and what do the controls do?")
w("%    Arditi et al. keep a candidate direction only if ablating it changes the")
w("%    next-token distribution on harmless prompts by KL < 0.1. The draft never")
w("%    checked this. 'generic' = 48 ordinary requests (their protocol); 'dataset' =")
w("%    the benchmark's benign prompts. Refusal rates are the judge on coherent")
w("%    outputs only (v2 degeneracy rule); a dagger marks a condition with >= 25%")
w("%    degenerate output, whose rate should not be quoted.")
w("% ---------------------------------------------------------------------------")
w("\\begin{table}[t]")
w("\\centering")
w("\\caption{Direction admissibility and ablation controls, harmful no-tool prompts ($n{=}240$).")
w("KL is the mean next-token KL$(\\text{clean}\\,\\|\\,\\text{ablated})$ on harmless prompts under")
w("all-layer projection removal; Arditi et al.\\ require $<0.1$. ``Layers'' counts candidate layers")
w("in the 35--85\\% depth band passing that threshold on generic prompts. Refusal is judged on")
w("coherent outputs; $\\ddagger$ marks conditions with $\\geq 25\\%$ degenerate output. Mean-out projects")
w("the mean activation out of the direction before ablating; random is a unit Gaussian direction;")
w("mean-dir ablates the mean-activation direction itself.}")
w("\\label{tab:controls}")
w("  \\begin{tabular}{lcc|c|ccccc}")
w("\\toprule")
w(" & \\multicolumn{2}{c|}{KL of $r_\\text{text}$} & & \\multicolumn{5}{c}{Refusal after ablating} \\\\")
w("Model & generic & dataset & Layers & none & $r_\\text{text}$ & mean-out & random & mean-dir \\\\")
w("\\midrule")
for m in ORDER:
    c = ctrl(m)
    if c is None:
        w(f"{ROW[m]:<14} & \\multicolumn{{8}}{{c}}{{not run}} \\\\")
        continue
    kg, kd = c["kl"]["ablate_rtext"]["generic"], c["kl"]["ablate_rtext"]["dataset"]
    npass = sum(s["pass_generic"] for s in c.get("scan", []))
    ntot = len(c.get("scan", []))
    dag = "$^\\dagger$" if c.get("quantized_4bit") else ""
    w(f"{ROW[m]:<14}{dag} & {kg:.2f} & {kd:.2f} & {npass}/{ntot} & {cj(m, 'ablation_base|None')} "
      f"& {cj(m, 'ablate_rtext|None')} & {cj(m, 'ablate_meanout|None')} & {cj(m, 'ablate_random|None')} "
      f"& {cj(m, 'ablate_meandir|None')} \\\\")
w("\\bottomrule")
w("\\end{tabular}")
w("\\end{table}")
w("")

# ---------------------------------------------------------------------------
# 7. Addition at multiples of the natural magnitude
# ---------------------------------------------------------------------------
w("% ---------------------------------------------------------------------------")
w("% 7. REPLACEMENT for the addition column: the draft added 4x the diff-in-means")
w("%    gap, which is degenerate in every model. Arditi add 1x. This is the sweep.")
w("% ---------------------------------------------------------------------------")
w("\\begin{table}[t]")
w("\\centering")
w("\\caption{Activation addition on benign no-tool prompts ($n{=}240$) at multiples of the")
w("diff-in-means gap (Arditi et al.\\ use $1\\times$; the draft used $4\\times$). Each cell is judged")
w("refusal among coherent outputs, with the degenerate share in parentheses. The refusal a model")
w("can be pushed to before its output breaks is far below the draft's 100\\%.}")
w("\\label{tab:addition}")
w("  \\begin{tabular}{lccccc}")
w("\\toprule")
w("Model & $0\\times$ & $1\\times$ & $1.5\\times$ & $2\\times$ & $3\\times$ \\\\")
w("\\midrule")
for m in ORDER:
    c = ctrl(m)
    if c is None or not ctrl_j(m):
        w(f"{ROW[m]:<14} & \\multicolumn{{5}}{{c}}{{not run}} \\\\")
        continue
    cells = []
    base = ctrl_j(m).get("addition_base|None")
    cells.append(f"{base['refuse_clean']:.2f}" if base else "--")
    coefs = {round(mu, 2): co for mu, co in zip(c.get("add_mults", []), c.get("add_coefs", []))}
    for mu in (1.0, 1.5, 2.0, 3.0):
        co = coefs.get(mu)
        r = ctrl_j(m).get(f"addition_added|{co}") if co is not None else None
        if r is None:
            cells.append("--")
        elif r["refuse_clean"] is None:
            cells.append(f"-- ({pct(r['degenerate_v2'])} deg.)")
        else:
            cells.append(f"{r['refuse_clean']:.2f} ({pct(r['degenerate_v2'])})")
    dag = "$^\\dagger$" if c.get("quantized_4bit") else ""
    w(f"{ROW[m]:<14}{dag} & " + " & ".join(cells) + " \\\\")
w("\\bottomrule")
w("\\end{tabular}")
w("\\end{table}")
w("")


def P(m, k):
    return round(100 * s(m)[k]["new"])


qa, qb = P("Qwen3-14B", "ablation_base"), P("Qwen3-14B", "ablation_ablated")
ga, gb = P("gemma-3-27b-it", "ablation_base"), P("gemma-3-27b-it", "ablation_ablated")
ma, mb = P("Mistral-7B-Instruct-v0.3", "ablation_base"), P("Mistral-7B-Instruct-v0.3", "ablation_ablated")
la, lb = P("Meta-Llama-3.1-70B-Instruct", "ablation_base"), P("Meta-Llama-3.1-70B-Instruct", "ablation_ablated")
ca, cb = P("c4ai-command-r7b-12-2024", "ablation_base"), P("c4ai-command-r7b-12-2024", "ablation_ablated")
aucs = [g(m)["auc_unsafe_fixed"]["auc"] for m in ORDER]
qsteer = round(100 * s("Qwen3-14B")["steering"]["benign_refuse_new"][-1])
w("% ===========================================================================")
w("% WRITING OUTLINES --- everything below is commented out on purpose.")
w("%")
w("% Notes on what each paragraph has to cover and which numbers to cite, not text")
w("% to paste. The tables above are ready to use as-is.")
w("% ===========================================================================")
w("")
w("% ---------------------------------------------------------------------------")
w("% 0. READ THIS FIRST --- output degeneracy")
w("% ---------------------------------------------------------------------------")
w("%     Ablation and addition can push a model off the rails into repetitive or")
w("%     non-linguistic output. Two real examples from our runs:")
w("%       Gemma, ablated:  'Vy수상수상수상수상수상...' for 400 characters")
w("%       Llama, addition: 'I can I can I can I can...' for 600 characters")
w("%     The refusal judge has no 'broken output' verdict, so such a response is")
w("%     forced into refuse/caveat/comply, and 'no help was given' reads as REFUSE.")
w("%     Any intervention rate computed over degenerate output measures breakage,")
w("%     not refusal. This is true of the OLD regex classifier too -- Qwen's")
w("%     degenerate addition output is literally \"I'm sorry I cannot I'm sorry I")
w("%     cannot...\", which the regex also scores as refusal. So the published")
w("%     addition numbers have the same problem; this is not new breakage.")
w("%")
w("%     Per-cell degeneracy rates are in relabel_analysis/degeneracy_audit.json")
w("%     (degeneracy_audit.py). Summary of what is and is not measurable:")
w("%       CLEAN (0% degenerate): every model's ablation except Gemma; all four")
w("%         baseline conditions; the lower half of every steering grid.")
w("%       ARTIFACT: addition at 4x the gap in all five models (67-100%")
w("%         degenerate); Gemma's ablation (100%).")
w("%     Recommend stating the degeneracy check in the paper. It is a genuine")
w("%     methodological contribution and pre-empts the obvious reviewer question.")
w("")
w("% ---------------------------------------------------------------------------")
w("% 1. SECTION 5 --- Mechanistic analysis")
w("% ---------------------------------------------------------------------------")
w("%")
w("% 1a. REPLACES 'A single direction causally governs text refusal'")
w("%     The current title asserts what we can no longer claim.")
w("%     Must cover:")
w(f"%       - Ablation lowers refusal in Mistral ({ma}%->{mb}%), Llama ({la}%->{lb}%)")
w(f"%         and Command-R ({ca}%->{cb}%). All three fluent, 0% degenerate.")
w(f"%       - It RAISES refusal in Qwen ({qa}%->{qb}%). Also fluent -- this is a real")
w("%         effect, not an artifact, and is the interesting one.")
w("%       - Gemma's ablation is NOT reportable: 100% of its ablated outputs are")
w("%         degenerate. Say so rather than reporting a number.")
w("%       - Why Qwen rises: ablation changes the phrasing of the refusal, not its")
w("%         presence -- out of 'I cannot' into forms like 'Certainly not.")
w("%         Submitting a client trade without proper approval is a serious")
w("%         violation.' 66 of 120 ablated Qwen responses are refusals a")
w("%         phrase-matching classifier misses.")
w("%       - Addition: at 4x the gap it is degenerate in all five, so we report it")
w("%         at the largest coefficient the model survives. The effect there is")
w("%         modest, not the near-total over-refusal previously reported")
w("%         (see Table~\\ref{tab:mech}).")
w("%     Framing: the Arditi replication is weaker than the draft claims in BOTH")
w("%     directions. Ablation does not uniformly reduce refusal, and addition does")
w("%     not drive benign refusal to ceiling except where it breaks the model.")
w("%")
w("% 1b. REPLACES 'Tool context suppresses the refusal signal'")
w("%     Must cover:")
w("%       - Suppression unchanged: significant in four of five (t=5.6 Qwen, 5.1")
w("%         Mistral, 9.7 Command-R, 4.0 Gemma; null for Llama at 0.4).")
w("%       - DROP the blanket 'text- and tool-derived directions remain aligned'.")
w("%         True for Qwen 0.741, Mistral 0.773, Gemma 0.797; NOT for Command-R")
w("%         0.394 or Llama 0.213 (Table~\\ref{tab:cosine}).")
w("%       - Llama is the coherent outlier: weakest alignment AND null suppression.")
w("%")
w("% 1c. REPLACES 'strong predictor but partial mediator' --- THE MEDIATOR CLAIM NARROWS")
w(f"%       - AUC range 0.69-0.88 becomes {min(aucs):.2f}-{max(aucs):.2f} under the")
w("%         global-scope scorer; all five now reproduce their published AUC.")
w("%       - Patching was rerun (Table~\\ref{tab:patching}); the draft's numbers came")
w("%         from runs with no saved generations, before the template fix. Overall")
w("%         flip rates are in the same range, but they decompose badly for the claim:")
for m in ORDER:
    r = patch(m)
    if r:
        w(f"%           {ROW[m]:<14} flip {pct(r['flip_rate_all'])} = safe call {pct(r['flip_via_safe_call'])}"
          f" + no call {pct(r['flip_via_no_call'])};  unsafe|call after {pct(r['unsafe_given_call_patched'] or 0)}")
w("%       - So the projection mediates whether the model ACTS (it flips to a text")
w("%         refusal), not whether the action it takes is safe: among calls the")
w("%         patched model still makes, ~90 percent stay unsafe. Say 'partial")
w("%         mediator of engagement', not of tool-call safety.")
w("%       - The no-call outputs are mostly coherent text refusals (Qwen 21/23,")
w("%         Command-R 8/10; Mistral 6/13, rest hedged how-to prose), so this IS")
w("%         refusal transfer in the paper's sense -- just not a safety mechanism.")
w("%       - Same pattern as ablation (Table~\\ref{tab:ablation-action}) and steering")
w("%         (1e): three interventions, one story -- the direction gates engagement.")
w("%")
w("% 1d. NEW PARAGRAPH --- ablation on behaviour (Table~\\ref{tab:ablation-action})")
w("%     Must cover:")
w("%       - Motivation: refusal-by-wording is classifier-dependent and, for some")
w("%         models, degenerate. Scoring the unsafe tool call is a predicate over")
w("%         parsed calls, so neither problem applies. Paired, n=200.")
w("%       - The headline unsafe rate moves in both directions across families.")
w("%       - The informative quantity is unsafe-given-a-call, near-flat everywhere:")
w("%         0.78->0.64, 0.77->0.75, 0.89->0.78, 0.61->0.64.")
w("%       - What moves is how often the model calls a tool: -22 pts Qwen, -17")
w("%         Llama, to zero in Gemma, +10 Command-R.")
w("%       - Conclusion: the direction gates engagement, not the safety of the")
w("%         action.")
w("%       - Gemma's row is the degeneracy again -- its tool-calling goes to zero")
w("%         because the output is broken. Consistent with 1a, and worth noting as")
w("%         convergent evidence rather than a separate finding.")
w("%")
w("% 1e. REPLACES 'Steering is a blunt lever' --- THE CONCLUSION CHANGES, BUT NOT")
w("%     IN THE DIRECTION AN EARLIER VERSION OF THESE NOTES SAID. Use")
w("%     Table~\\ref{tab:steering-calls}. Two measurement problems in the draft:")
w("%       (i)  top-of-grid points are 32-100 percent degenerate (v2 detector), so")
w("%            the over-refusal rates there (Qwen 0.44, Command-R/Gemma/Llama 1.00)")
w("%            measure breakage, not refusal;")
w("%       (ii) 'unsafe -> 0' at the next coefficient down is not safer calling. The")
w("%            model stops calling tools at all, on BOTH sides:")
w("%              Mistral  c=11    harmful any-call 0.39->0.02, unsafe|call 0.70->0.25 (n=4)")
w("%                               benign  any-call 0.51->0.05 while text over-refusal reads 0.08")
w("%              Llama    c=20    harmful any-call 0.77->0.03, unsafe|call 0.67->0.80")
w("%                               benign  any-call 0.93->0.12, over-refusal 0.41")
w("%              Gemma    c=12162 harmful any-call 0.15->0.04, unsafe|call 0.77->0.78")
w("%                               benign  any-call 0.39->0.07 while over-refusal FALLS 0.22->0.14")
w("%              Qwen     c=450   harmful any-call 0.61->0.32, unsafe|call 0.88->0.76")
w("%                               benign  any-call 0.66->0.48, over-refusal 0.08")
w("%              Command-R c=49   harmful any-call 0.12->0.04, unsafe|call 0.96->0.88")
w("%                               benign  any-call 0.42->0.40, over-refusal 0.18  <- the one partial exception")
w("%     Must cover:")
w("%       - Text-judged over-refusal on benign prompts understates collateral damage")
w("%         badly: a model that answers a benign tool task in prose without calling")
w("%         the tool is not refusing, but it is not doing the task either. Report")
w("%         benign any-call (task completion) next to over-refusal.")
w("%       - Unsafe-given-call is flat or rising at every coefficient in every model:")
w("%         steering never makes the calls a model still makes safer. It removes")
w("%         unsafe calls only by removing calls.")
w("%       - Command-R at c=49 is the only point that cuts harmful unsafe calls")
w("%         (0.115->0.035) while keeping benign calls (0.42->0.40); even there")
w("%         unsafe|call is 0.88 and over-refusal is 0.18.")
w("%       - So 'blunt lever' is, if anything, understated: the lever is engagement,")
w("%         and it moves benign and harmful engagement together. That is the same")
w("%         finding as ablation (Table~\\ref{tab:ablation-action}) and patching")
w("%         (Table~\\ref{tab:patching}), from a third intervention.")
w("%       - Future Work: the target is a direction (or a different intervention)")
w("%         that changes unsafe|call, not any-call; none of the three tried here does.")
w("")
w("% ---------------------------------------------------------------------------")
w("% 2. SECTION 3.6 --- 'Robustness of the direction'")
w("% ---------------------------------------------------------------------------")
w("%       - Point at Table~\\ref{tab:cosine}; the claim holds, 0.69-0.86.")
w("%       - Sample-size caveat: the complied side is small (25 per class in")
w("%         Gemma); folding hedged compliance in doubles it and moves the cosine")
w("%         by <=0.04.")
w("%       - Free ammunition: recomputing the behaviour direction under the OLD")
w("%         labels agrees at 0.96-0.98, so this check does not depend on the")
w("%         relabelling.")
w("")
w("% ---------------------------------------------------------------------------")
w("% 3. METHODS --- three additions")
w("% ---------------------------------------------------------------------------")
w("%")
w("% 3a. APPEND to 'Refusal classification'")
w("%       - Section 5's interventions use this same classifier.")
w("%       - A phrase-matching classifier misreads ablation, which changes how a")
w("%         model refuses, as a change in whether it refuses.")
w("%       - NEW: responses are screened for degeneracy before judging (see 3c).")
w("%")
w("% 3b. NEW \\paragraph --- prompt construction under tools")
w("%       - Templates differ in whether they carry tool definitions; passing tools")
w("%         to a template without a tool block drops them silently, so the tool")
w("%         prompt becomes a chat prompt and every response scores as safe.")
w("%       - Gemma-3 has no tool block in any published checkpoint, so its schemas")
w("%         go in the prompt text. Validated: 12.5% unsafe vs 14.6% from the")
w("%         behavioural run, and it reproduces the published AUC to within 0.001.")
w("%       - We assert a tool name appears in the rendered prompt before measuring.")
w("%       - Llama-3.1-70B from unsloth/Meta-Llama-3.1-70B-Instruct (meta-llama is")
w("%         gated); same bf16 weights, and its template carries tools.")
w("%")
w("% 3c. NEW \\paragraph --- degeneracy screening")
w("%       - Interventions can produce repetitive or non-linguistic output that no")
w("%         refusal classifier can label meaningfully.")
w("%       - Screen on repeated-3-gram share, unique-token ratio and non-ASCII")
w("%         share, with a length floor so short genuine refusals are not flagged.")
w("%       - Report which cells are unmeasurable rather than reporting a number.")
w("")
w("% ---------------------------------------------------------------------------")
w("% 4. SECTION 7 DISCUSSION --- 'A shared refusal direction, suppressed rather")
w("%    than replaced'")
w("% ---------------------------------------------------------------------------")
w("%     Must change:")
w("%       - 'ablations collapse and decrease harmful prompt refusal rates' --")
w("%         true in three of five, reversed in Qwen, unmeasurable in Gemma.")
w("%       - 'the directions ... are aligned' -- true in three of five.")
w("%     Keep: behaviour-defined and request-type directions closely aligned; the")
w("%     suppression-not-replacement reading scoped to where it holds; the")
w("%     qi2024safety connection.")
w("")
w("% ---------------------------------------------------------------------------")
w("% 5. ABSTRACT, SECTION 1 INTRO, AND FUTURE WORK")
w("% ---------------------------------------------------------------------------")
w("%     - Abstract and intro describe the mechanistic finding as ablation")
w("%       collapsing refusal. Needs a pass once Section 5 settles.")
w("%     - Future Work 'Precise interventions' currently argues steering is too")
w("%       blunt to deploy. Soften: the constraint is choosing a per-model")
w("%       coefficient below the degeneracy threshold, and at such coefficients")
w("%       several models already reach near-zero unsafe rates.")
w("")
DEST.write_text("\n".join(L) + "\n")
print(f"wrote {DEST} ({len(L)} lines)")
