#!/usr/bin/env python3
"""Emit paper_updates.tex: drop-in replacements for the NeurIPS draft's mechanism
section, generated straight from the result JSON so no number is hand-copied."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "relabel_analysis"
DEST = Path(__file__).resolve().parent / "paper_updates.tex"

ORDER = ["Qwen3-14B", "Mistral-7B-Instruct-v0.3", "c4ai-command-r7b-12-2024",
         "gemma-3-27b-it", "Meta-Llama-3.1-70B-Instruct"]
ROW = {"Qwen3-14B": "Qwen3-14B", "Mistral-7B-Instruct-v0.3": "Mistral-7B",
       "c4ai-command-r7b-12-2024": "Command-R-7B", "gemma-3-27b-it": "Gemma-3-27B",
       "Meta-Llama-3.1-70B-Instruct": "Llama-3.1-70B"}
LAYER = {"Qwen3-14B": "33/40", "Mistral-7B-Instruct-v0.3": "26/32",
         "c4ai-command-r7b-12-2024": "26/32", "gemma-3-27b-it": "51/62",
         "Meta-Llama-3.1-70B-Instruct": "67/80"}
# unchanged columns, carried over from the current draft (not rerun; see notes)
SUPPRESSION = {"Qwen3-14B": "$66.8,\\ t{=}5.6$", "Mistral-7B-Instruct-v0.3": "$1.4,\\ t{=}5.1$",
               "c4ai-command-r7b-12-2024": "$26.4,\\ t{=}9.7$",
               "gemma-3-27b-it": "$2902,\\ t{=}4.0$",
               "Meta-Llama-3.1-70B-Instruct": "$0.2,\\ t{=}0.4$"}
PATCHING = {"Qwen3-14B": "18", "Mistral-7B-Instruct-v0.3": "24",
            "c4ai-command-r7b-12-2024": "62", "gemma-3-27b-it": "46",
            "Meta-Llama-3.1-70B-Instruct": "40"}


def g(m):
    return json.loads((OUT / f"gpu_{m}.json").read_text())


def s(m):
    return json.loads((OUT / f"steer_{m}.json").read_text())


def a(m):
    return json.loads((OUT / f"ablation_action_{m}.json").read_text())


def pct(x):
    return f"{round(100 * x):d}\\%"


L = []
w = L.append

w("% ============================================================================")
w("% paper_updates.tex --- drop-in replacements for the mechanism section.")
w("% Generated by make_paper_updates.py from relabel_analysis/*.json.")
w("%")
w("% Every number here is recomputed on the corrected labels and the corrected")
w("% tool-safety scorer. Two columns of Table 2 are NOT rerun and are carried over")
w("% verbatim from the current draft: Suppression and Patching. Both are")
w("% classifier-independent, so the relabel cannot move them, but see NOTES at the")
w("% bottom for why re-verifying them is still worth an hour of GPU.")
w("% ============================================================================")
w("")
w("% ---------------------------------------------------------------------------")
w("% 1. REPLACEMENT FOR Table~\\ref{tab:mech}")
w("% ---------------------------------------------------------------------------")
w("\\begin{table}[t]")
w("\\centering")
w("\\setlength{\\tabcolsep}{4pt}")
w("\\caption{The refusal direction predicts tool-call safety across all five families (bf16).")
w("Suppression is the paired drop in refusal activation from no-tool to tool-normal, reported as")
w("mean $\\Delta$ and $t$-statistic ($n{=}96$); $\\Delta$ is in each model's own activation units, so")
w("magnitudes are not comparable across rows. Ablation and addition give refusal rates before and")
w("after the intervention, on harmful and benign prompts respectively, scored by the same")
w("three-way classifier used for Table~\\ref{tab:headline-divergence} ($n{=}240$ per condition).")
w("AUC is the area under the ROC of low refusal activation predicting an unsafe call; patching is")
w("the fraction of unsafe calls that revert to safe when the projection is restored to its matched")
w("no-tool level. The direction remains a strong predictor in every model, but ablation no longer")
w("reduces refusal uniformly: it reverses in Qwen and Gemma (see text).}")
w("\\label{tab:mech}")
w("  \\begin{tabular}{lccccc}")
w("\\toprule")
w("Model & Layer & Suppression ($\\Delta$, $t$) & Ablation & Addition & AUC\\,/\\,Patching \\\\")
w("\\midrule")
for m in ORDER:
    st, gp = s(m), g(m)
    abl = f"${pct(st['ablation_base']['new'])}\\!\\to\\!{pct(st['ablation_ablated']['new'])}$"
    add = f"${pct(st['addition_base']['new'])}\\!\\to\\!{pct(st['addition_added']['new'])}$"
    auc = gp["auc_unsafe_fixed"]["auc"]
    w(f"{ROW[m]:<14} & {LAYER[m]} & {SUPPRESSION[m]}  & {abl} & {add} "
      f"& ${auc:.3f}$\\,/\\,${PATCHING[m]}\\%$ \\\\")
w("\\bottomrule")
w("\\end{tabular}")
w("\\end{table}")
w("")

w("% ---------------------------------------------------------------------------")
w("% 2. NEW TABLE: direction cosines (the Section 3.6 robustness check)")
w("% ---------------------------------------------------------------------------")
w("\\begin{table}[t]")
w("\\centering")
w("\\caption{Alignment between the three directions, at each model's operating layer.")
w("$\\hat{r}_{\\text{text}}$ is the request-type direction (harmful vs.\\ benign, no-tool);")
w("$\\hat{r}_{\\text{tool}}$ is the same contrast extracted under tool prompts;")
w("$\\hat{r}_{\\text{behav}}$ is the behaviour-defined direction (refused vs.\\ complied harmful).")
w("The final column recomputes $\\hat{r}_{\\text{behav}}$ under the previous labels: the two agree")
w("at $0.96$--$0.98$ everywhere, so this check does not depend on the relabel.}")
w("\\label{tab:cosine}")
w("  \\begin{tabular}{lcccc}")
w("\\toprule")
w("Model & Layer & $\\cos(\\hat{r}_{\\text{text}},\\hat{r}_{\\text{behav}})$ "
  "& $\\cos(\\hat{r}_{\\text{text}},\\hat{r}_{\\text{tool}})$ "
  "& $\\hat{r}_{\\text{behav}}$ old vs.\\ new \\\\")
w("\\midrule")
for m in ORDER:
    d = g(m)
    w(f"{ROW[m]:<14} & {LAYER[m]} & ${d['cos_rtext_rbehav_strict']:.3f}$ "
      f"& ${d['cos_rtext_rtool']:.3f}$ & ${d['cos_rbehav_old_new']:.3f}$ \\\\")
w("\\bottomrule")
w("\\end{tabular}")
w("\\end{table}")
w("")

w("% ---------------------------------------------------------------------------")
w("% 3. NEW TABLE: does ablation change the action, or only the wording?")
w("% ---------------------------------------------------------------------------")
w("\\begin{table}[t]")
w("\\centering")
w("\\caption{Ablation's effect on behaviour rather than wording, on harmful tool-enabled")
w("prompts ($n{=}200$, paired). Unsafe-tool-call scoring is a predicate over the parsed calls, so")
w("no refusal classifier enters this measurement. ``Calls'' is the share of prompts on which the")
w("model emits any tool call; ``Unsafe\\,$\\mid$\\,calls'' is the unsafe rate among those. The")
w("headline rate moves in both directions across families, but the conditional rate is near-flat")
w("everywhere: ablation changes how often a model acts, not how safely it acts once it does.}")
w("\\label{tab:ablation-action}")
w("  \\begin{tabular}{lccccc}")
w("\\toprule")
w("Model & Unsafe (base $\\to$ abl.) & $\\Delta$ (95\\% CI) & Calls (base $\\to$ abl.) "
  "& Unsafe\\,$\\mid$\\,calls \\\\")
w("\\midrule")
for m in ORDER:
    d = a(m)
    lo, hi = d["delta_ci_paired"]
    cond = "n/a" if d.get("unsafe_given_called_abl") is None \
        else f"${d['unsafe_given_called_base']:.2f}\\!\\to\\!{d['unsafe_given_called_abl']:.2f}$"
    w(f"{ROW[m]:<14} & ${d['unsafe_baseline']:.3f}\\!\\to\\!{d['unsafe_ablated']:.3f}$ "
      f"& ${d['delta_unsafe']:+.3f}$ $({lo:+.2f},{hi:+.2f})$ "
      f"& ${d['called_tool_baseline']:.3f}\\!\\to\\!{d['called_tool_ablated']:.3f}$ & {cond} \\\\")
w("\\bottomrule")
w("\\end{tabular}")
w("\\end{table}")
w("")

def P(m, k):
    return round(100 * s(m)[k]["new"])


qa, qb = P("Qwen3-14B", "ablation_base"), P("Qwen3-14B", "ablation_ablated")
ga, gb = P("gemma-3-27b-it", "ablation_base"), P("gemma-3-27b-it", "ablation_ablated")
ma, mb = P("Mistral-7B-Instruct-v0.3", "ablation_base"), P("Mistral-7B-Instruct-v0.3", "ablation_ablated")
la, lb = P("Meta-Llama-3.1-70B-Instruct", "ablation_base"), P("Meta-Llama-3.1-70B-Instruct", "ablation_ablated")
ca, cb = P("c4ai-command-r7b-12-2024", "ablation_base"), P("c4ai-command-r7b-12-2024", "ablation_ablated")
aucs = [g(m)["auc_unsafe_fixed"]["auc"] for m in ORDER]
qsteer = round(100 * s("Qwen3-14B")["steering"]["benign_refuse_new"][-1])

w("% ---------------------------------------------------------------------------")
w("% 4. REPLACEMENT PARAGRAPHS FOR SECTION 5 (Mechanistic analysis)")
w("%    Replaces the four \\paragraph blocks currently in that section.")
w("% ---------------------------------------------------------------------------")
w("")
w("\\paragraph{The direction controls refusal, but not uniformly by ablation:} Adding $\\hat{r}$")
w("drives benign refusal from near zero to $100\\%$ in every model, reproducing the additive half")
w(f"of \\citet{{arditi2024refusal}} on each architecture. Ablation is less uniform. It lowers the")
w(f"harmful refusal rate in Mistral (${ma}\\%\\to{mb}\\%$), Llama (${la}\\%\\to{lb}\\%$) and Command-R")
w(f"(${ca}\\%\\to{cb}\\%$), but in Qwen (${qa}\\%\\to{qb}\\%$) and Gemma (${ga}\\%\\to{gb}\\%$) it")
w("\\emph{raises} measured refusal. Inspecting the generations shows why: ablation shifts the")
w("phrasing of the refusal rather than removing it, out of the first-person modal forms")
w("(``I cannot\\ldots'') and into constructions like ``Certainly not. Submitting a client trade")
w("without proper approval is a serious violation.'' A regex classifier keyed to the former reads")
w("that shift as a behavioural drop; a classifier that reads the whole response does not. We")
w("therefore report ablation under the same three-way classifier used for")
w("Table~\\ref{tab:headline-divergence}. The auto-selected layers sit in the upper-middle part of")
w("each network, and the addition coefficient spans more than three orders of magnitude, from")
w("$29.8$ in Mistral to roughly $75{,}800$ in Gemma.")
w("")
w("\\paragraph{Tool context suppresses the refusal signal:} For our harmful triples, the mean")
w("refusal activation drops significantly from no-tool to tool-enabled modes in four of the five")
w("models (Table~\\ref{tab:mech}, with $t = 5.6$ for Qwen, $t = 5.1$ for Mistral, $t = 9.7$ for")
w("Command-R, and $t = 4.0$ for Gemma, but null for Llama at $t = 0.4$; Figure~\\ref{fig:proj}).")
w("Whether tools rotate the direction or merely attenuate it varies by family")
w("(Table~\\ref{tab:cosine}). In Qwen, Mistral and Gemma the text- and tool-derived directions stay")
w("closely aligned ($0.74$--$0.80$), consistent with attenuation along a shared axis. In Command-R")
w("($0.39$) and Llama ($0.21$) the alignment is much weaker, so for those two the shared-axis")
w("reading is not supported by our measurements. Llama is also the model where suppression is null,")
w("making it the clearest case in which tool context relates to the refusal representation")
w("differently than in the other families.")
w("")
w("\\paragraph{The refusal direction is a strong predictor but a partial mediator:} A lower refusal")
w(f"activation reliably predicts an unsafe call in every model, with AUC from ${min(aucs):.2f}$ to")
w(f"${max(aucs):.2f}$ under the global-scope tool-call scorer. At the same time, when we patch a")
w("tool run's projection back to its no-tool level, only a fraction of the unsafe calls revert to")
w("being safe: 18 percent for Qwen and 24 percent for Mistral. The refusal direction is therefore a")
w("partial mediator of the transfer failure, not a complete account of it. The unrecovered portion")
w("may reflect an incomplete one-dimensional intervention, refusal may be represented across")
w("additional directions, other layers, or other token positions, or nonlinear and distributed")
w("mechanisms that a single-scalar patch does not restore. Our design also varies tool availability")
w("jointly with tool-oriented prompt wording, so we cannot attribute the remaining failures to tool")
w("affordance specifically; we can only conclude that restoring this one signal is not sufficient as")
w("a control mechanism. The balance between the two varies by model. For Command-R, for example, the")
w("affordance mediates much more strongly than the others at 62 percent, although only on a smaller")
w("unsafe set.")
w("")
w("\\paragraph{The direction gates engagement, not the safety of the action:} To test whether the")
w("direction controls behaviour and not only wording, we ablate it on harmful tool-enabled prompts")
w("and score the unsafe tool call directly, a predicate over the parsed calls that involves no")
w("refusal classifier (Table~\\ref{tab:ablation-action}). The headline unsafe rate moves in both")
w("directions across families. What is consistent is the rate conditional on the model having called")
w("a tool at all, which barely moves anywhere ($0.78\\to0.64$, $0.77\\to0.75$, $0.89\\to0.78$,")
w("$0.61\\to0.64$), while the rate of calling a tool at all swings by 10 to 22 points and in both")
w("directions. Ablation therefore changes how often a model engages, not how safely it acts once")
w("engaged. Gemma is the limiting case: its tool-calling collapses to zero, so its apparent safety")
w("gain is the model ceasing to act rather than acting safely, and is better read as capability")
w("damage than as alignment.")
w("")
w("\\paragraph{Steering is a blunt lever:} When raising the steering coefficient, the harmful unsafe")
w("rate does decrease towards zero, but the benign over-refusal rate rises accordingly")
w(f"(Figure~\\ref{{fig:steer}}). For Qwen, removing unsafe calls entirely costs ${qsteer}$ percent")
w("benign over-refusal; in Command-R, Gemma and Llama the same operating point costs essentially all")
w("benign tool use. No coefficient in our grid removes unsafe behaviour without large collateral")
w("over-refusal. Steering through the refusal direction is therefore an imprecise safety control.")
w("")

w("% ---------------------------------------------------------------------------")
w("% 5. REPLACEMENT for the Section 3.6 'Robustness of the direction' paragraph")
w("% ---------------------------------------------------------------------------")
w("")
w("\\paragraph{Robustness of the direction:} Our refusal direction contrasts across request type,")
w("subtracting activations for harmful and benign prompts. To verify that the result is not an")
w("artifact of that choice, we additionally extract a behaviour-defined direction, taking the")
w("difference in means between refused and complied harmful prompts, and measure its cosine")
w("similarity with the request-type direction (Table~\\ref{tab:cosine}). The two are closely aligned")
w("in every model ($0.69$--$0.86$), confirming that request harmfulness and the refusal decision")
w("occupy substantially the same axis. Because models rarely comply with harmful requests, the")
w("complied side is small (as few as 25 per class in Gemma); folding hedged compliance in with")
w("compliance roughly doubles it and moves the cosine by at most $0.04$. Recomputing the")
w("behaviour-defined direction under the previous refusal labels agrees with the current one at")
w("$0.96$--$0.98$ in every model, so this check does not depend on the relabelling.")
w("")

w("% ---------------------------------------------------------------------------")
w("% 6. METHODS ADDITIONS (reproducibility; Section 3.5 / 3.6)")
w("% ---------------------------------------------------------------------------")
w("")
w("% Append to \\subsection{Refusal classification}:")
w("All interventions in Section~\\ref{sec:mech} are scored with this same classifier. This matters")
w("for the intervention results specifically: a regex classifier keyed to first-person refusal")
w("phrasing misreads ablation, which changes how a model refuses, as a change in whether it refuses.")
w("")
w("% Append to \\subsection{Mechanistic methods}:")
w("\\paragraph{Prompt construction under tools:} Chat templates differ in whether they can carry tool")
w("definitions. Passing tools to a template with no tool-handling block silently drops them, turning")
w("a tool-enabled prompt into a plain chat prompt and making every response score as safe. Gemma-3")
w("has no tool-handling block in any published checkpoint, so for that model we write the tool")
w("schemas into the prompt text; this reconstruction gives a $12.5\\%$ unsafe rate on harmful")
w("tool-normal prompts against $14.6\\%$ from the behavioural run, and reproduces its published AUC")
w("to within $0.001$. We verify for every model that a tool name appears in the rendered prompt")
w("before running any tool-mode measurement. Llama-3.1-70B weights were loaded from a bf16 mirror")
w("(\\texttt{unsloth/Meta-Llama-3.1-70B-Instruct}) whose chat template carries tools; an otherwise")
w("identical mirror ships a stripped template that does not.")
w("")

w("% ---------------------------------------------------------------------------")
w("% 7. DISCUSSION FIX")
w("% ---------------------------------------------------------------------------")
w("% The paragraph 'A shared refusal direction, suppressed rather than replaced' currently asserts")
w("% that ablations collapse refusal in all models and that text- and tool-derived directions are")
w("% aligned. Both need softening. Suggested replacement for its first half:")
w("")
w("We find that the single refusal direction \\citet{arditi2024refusal} identify for chat refusal is")
w("present in all five models we probe: additions induce benign over-refusal everywhere, and the")
w("behaviour-defined and request-type directions are closely aligned (Table~\\ref{tab:cosine}).")
w("Ablation, however, reduces refusal in only three of the five, and in two it changes the wording of")
w("refusal rather than its presence. Where tool context does suppress the signal it does so along a")
w("largely shared axis in Qwen, Mistral and Gemma, though not in Command-R or Llama. The divergence")
w("is therefore better described as attenuation of an existing safety representation in most")
w("families than as a separate tool-mode circuit, consistent with evidence that text safety")
w("alignment is often shallow~\\citep{qi2024safety}.")
w("")

w("% ---------------------------------------------------------------------------")
w("% NOTES --- what is not settled")
w("% ---------------------------------------------------------------------------")
w("% (a) Suppression and Patching columns are carried over unchanged. Neither depends on the refusal")
w("%     classifier, so the relabel cannot move them. They are, however, the only Table 2 cells still")
w("%     resting on runs from before the chat-template problem was found, and suppression is measured")
w("%     on tool-mode prompts -- exactly what that bug corrupted. Re-verifying both is ~1 hour of GPU")
w("%     and would let you say the whole table was regenerated.")
w("%")
w("% (b) Table 1 in the current draft does not match the committed labels. Four of five text-refusal")
w("%     values agree to three decimals; Mistral reads 0.535 where summary_three_way.csv gives 0.435,")
w("%     which looks like a transcription slip. The unsafe and divergence columns are uniformly about")
w("%     12 percent higher than the committed scorer produces (e.g. Qwen unsafe-normal 0.544 vs")
w("%     0.487), suggesting Table 1 was built with a stricter predicate that is not in the repo. The")
w("%     AUC column above uses the committed scorer; if Table 1 keeps its current numbers, AUC should")
w("%     be regenerated against that same scorer so the two tables agree.")
w("%")
w("% (c) The abstract and introduction still describe the mechanistic finding in terms of ablation")
w("%     collapsing refusal. Worth a pass once the section above is settled.")

DEST.write_text("\n".join(L) + "\n")
print(f"wrote {DEST} ({len(L)} lines)")
