#!/usr/bin/env python3
"""Emit paper_updates.tex: drop-in replacements for the NeurIPS draft's mechanism
section, generated straight from the result JSON so no number is hand-copied."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "relabel_analysis"
DEST = Path(__file__).resolve().parent / "paper_updates.tex"

ORDER = ["Qwen3-14B", "Mistral-7B-Instruct-v0.3", "c4ai-command-r7b-12-2024",
         "gemma-3-27b-it", "Meta-Llama-3.1-70B-Instruct"]
ROW = {"Qwen3-14B": "Qwen3-14B", "Mistral-7B-Instruct-v0.3": "Mistral-7B",
       "c4ai-command-r7b-12-2024": "Command-R-7B", "gemma-3-27b-it": "Gemma-3-27B",
       "Meta-Llama-3.1-70B-Instruct": "Llama-3.1-70B"}
LAYER = {"Qwen3-14B": "33/40", "Mistral-7B-Instruct-v0.3": "26/32",
         "c4ai-command-r7b-12-2024": "26/32", "gemma-3-27b-it": "51/62",
         "Meta-Llama-3.1-70B-Instruct": "67/80"}
# unchanged columns, carried over from the current draft (not rerun; see notes)
SUPPRESSION = {"Qwen3-14B": "$66.8,\\ t{=}5.6$", "Mistral-7B-Instruct-v0.3": "$1.4,\\ t{=}5.1$",
               "c4ai-command-r7b-12-2024": "$26.4,\\ t{=}9.7$",
               "gemma-3-27b-it": "$2902,\\ t{=}4.0$",
               "Meta-Llama-3.1-70B-Instruct": "$0.2,\\ t{=}0.4$"}
PATCHING = {"Qwen3-14B": "18", "Mistral-7B-Instruct-v0.3": "24",
            "c4ai-command-r7b-12-2024": "62", "gemma-3-27b-it": "46",
            "Meta-Llama-3.1-70B-Instruct": "40"}


def g(m):
    return json.loads((OUT / f"gpu_{m}.json").read_text())


def s(m):
    return json.loads((OUT / f"steer_{m}.json").read_text())


def a(m):
    return json.loads((OUT / f"ablation_action_{m}.json").read_text())


def pct(x):
    return f"{round(100 * x):d}\\%"


L = []
w = L.append

w("% ============================================================================")
w("% paper_updates.tex --- drop-in replacements for the mechanism section.")
w("% Generated by make_paper_updates.py from relabel_analysis/*.json.")
w("%")
w("% The TABLES below are ready to paste. The WRITING OUTLINES after them are")
w("% commented-out notes on what each paragraph must cover and which numbers to")
w("% cite -- deliberately not drafted prose, so the text stays in the authors' voice.")
w("%")
w("% Every number is recomputed on the corrected labels and the corrected")
w("% tool-safety scorer. Two columns of Table 2 are NOT rerun and are carried over")
w("% verbatim from the current draft: Suppression and Patching. Both are")
w("% classifier-independent, so the relabel cannot move them, but see NOTES at the")
w("% bottom for why re-verifying them is still worth an hour of GPU.")
w("% ============================================================================")
w("")
w("% ---------------------------------------------------------------------------")
w("% 1. REPLACEMENT FOR Table~\\ref{tab:mech}")
w("% ---------------------------------------------------------------------------")
w("\\begin{table}[t]")
w("\\centering")
w("\\setlength{\\tabcolsep}{4pt}")
w("\\caption{The refusal direction predicts tool-call safety across all five families (bf16).")
w("Suppression is the paired drop in refusal activation from no-tool to tool-normal, reported as")
w("mean $\\Delta$ and $t$-statistic ($n{=}96$); $\\Delta$ is in each model's own activation units, so")
w("magnitudes are not comparable across rows. Ablation and addition give refusal rates before and")
w("after the intervention, on harmful and benign prompts respectively, scored by the same")
w("three-way classifier used for Table~\\ref{tab:headline-divergence} ($n{=}240$ per condition).")
w("AUC is the area under the ROC of low refusal activation predicting an unsafe call; patching is")
w("the fraction of unsafe calls that revert to safe when the projection is restored to its matched")
w("no-tool level. The direction remains a strong predictor in every model, but ablation no longer")
w("reduces refusal uniformly: it reverses in Qwen and Gemma (see text).}")
w("\\label{tab:mech}")
w("  \\begin{tabular}{lccccc}")
w("\\toprule")
w("Model & Layer & Suppression ($\\Delta$, $t$) & Ablation & Addition & AUC\\,/\\,Patching \\\\")
w("\\midrule")
for m in ORDER:
    st, gp = s(m), g(m)
    abl = f"${pct(st['ablation_base']['new'])}\\!\\to\\!{pct(st['ablation_ablated']['new'])}$"
    add = f"${pct(st['addition_base']['new'])}\\!\\to\\!{pct(st['addition_added']['new'])}$"
    auc = gp["auc_unsafe_fixed"]["auc"]
    w(f"{ROW[m]:<14} & {LAYER[m]} & {SUPPRESSION[m]}  & {abl} & {add} "
      f"& ${auc:.3f}$\\,/\\,${PATCHING[m]}\\%$ \\\\")
w("\\bottomrule")
w("\\end{tabular}")
w("\\end{table}")
w("")

w("% ---------------------------------------------------------------------------")
w("% 2. NEW TABLE: direction cosines (the Section 3.6 robustness check)")
w("% ---------------------------------------------------------------------------")
w("\\begin{table}[t]")
w("\\centering")
w("\\caption{Alignment between the three directions, at each model's operating layer.")
w("$\\hat{r}_{\\text{text}}$ is the request-type direction (harmful vs.\\ benign, no-tool);")
w("$\\hat{r}_{\\text{tool}}$ is the same contrast extracted under tool prompts;")
w("$\\hat{r}_{\\text{behav}}$ is the behaviour-defined direction (refused vs.\\ complied harmful).")
w("The final column recomputes $\\hat{r}_{\\text{behav}}$ under the previous labels: the two agree")
w("at $0.96$--$0.98$ everywhere, so this check does not depend on the relabel.}")
w("\\label{tab:cosine}")
w("  \\begin{tabular}{lcccc}")
w("\\toprule")
w("Model & Layer & $\\cos(\\hat{r}_{\\text{text}},\\hat{r}_{\\text{behav}})$ "
  "& $\\cos(\\hat{r}_{\\text{text}},\\hat{r}_{\\text{tool}})$ "
  "& $\\hat{r}_{\\text{behav}}$ old vs.\\ new \\\\")
w("\\midrule")
for m in ORDER:
    d = g(m)
    w(f"{ROW[m]:<14} & {LAYER[m]} & ${d['cos_rtext_rbehav_strict']:.3f}$ "
      f"& ${d['cos_rtext_rtool']:.3f}$ & ${d['cos_rbehav_old_new']:.3f}$ \\\\")
w("\\bottomrule")
w("\\end{tabular}")
w("\\end{table}")
w("")

w("% ---------------------------------------------------------------------------")
w("% 3. NEW TABLE: does ablation change the action, or only the wording?")
w("% ---------------------------------------------------------------------------")
w("\\begin{table}[t]")
w("\\centering")
w("\\caption{Ablation's effect on behaviour rather than wording, on harmful tool-enabled")
w("prompts ($n{=}200$, paired). Unsafe-tool-call scoring is a predicate over the parsed calls, so")
w("no refusal classifier enters this measurement. ``Calls'' is the share of prompts on which the")
w("model emits any tool call; ``Unsafe\\,$\\mid$\\,calls'' is the unsafe rate among those. The")
w("headline rate moves in both directions across families, but the conditional rate is near-flat")
w("everywhere: ablation changes how often a model acts, not how safely it acts once it does.}")
w("\\label{tab:ablation-action}")
w("  \\begin{tabular}{lccccc}")
w("\\toprule")
w("Model & Unsafe (base $\\to$ abl.) & $\\Delta$ (95\\% CI) & Calls (base $\\to$ abl.) "
  "& Unsafe\\,$\\mid$\\,calls \\\\")
w("\\midrule")
for m in ORDER:
    d = a(m)
    lo, hi = d["delta_ci_paired"]
    cond = "n/a" if d.get("unsafe_given_called_abl") is None \
        else f"${d['unsafe_given_called_base']:.2f}\\!\\to\\!{d['unsafe_given_called_abl']:.2f}$"
    w(f"{ROW[m]:<14} & ${d['unsafe_baseline']:.3f}\\!\\to\\!{d['unsafe_ablated']:.3f}$ "
      f"& ${d['delta_unsafe']:+.3f}$ $({lo:+.2f},{hi:+.2f})$ "
      f"& ${d['called_tool_baseline']:.3f}\\!\\to\\!{d['called_tool_ablated']:.3f}$ & {cond} \\\\")
w("\\bottomrule")
w("\\end{tabular}")
w("\\end{table}")
w("")

def P(m, k):
    return round(100 * s(m)[k]["new"])


qa, qb = P("Qwen3-14B", "ablation_base"), P("Qwen3-14B", "ablation_ablated")
ga, gb = P("gemma-3-27b-it", "ablation_base"), P("gemma-3-27b-it", "ablation_ablated")
ma, mb = P("Mistral-7B-Instruct-v0.3", "ablation_base"), P("Mistral-7B-Instruct-v0.3", "ablation_ablated")
la, lb = P("Meta-Llama-3.1-70B-Instruct", "ablation_base"), P("Meta-Llama-3.1-70B-Instruct", "ablation_ablated")
ca, cb = P("c4ai-command-r7b-12-2024", "ablation_base"), P("c4ai-command-r7b-12-2024", "ablation_ablated")
aucs = [g(m)["auc_unsafe_fixed"]["auc"] for m in ORDER]
qsteer = round(100 * s("Qwen3-14B")["steering"]["benign_refuse_new"][-1])
w("% ===========================================================================")
w("% WRITING OUTLINES --- everything below is commented out on purpose.")
w("%")
w("% These are notes on what each paragraph has to cover and which numbers to")
w("% cite, not text to paste. The tables above are ready to use as-is.")
w("% ===========================================================================")
w("")
w("% ---------------------------------------------------------------------------")
w("% 4. SECTION 5 --- Mechanistic analysis. Four paragraphs now, five after.")
w("% ---------------------------------------------------------------------------")
w("%")
w("% 4a. REPLACES 'A single direction causally governs text refusal'")
w("%     The current title asserts what we can no longer claim, so it needs to go.")
w("%     Must cover:")
w("%       - Addition works in all five models: near zero -> 100% benign refusal.")
w("%         This half of Arditi et al. reproduces cleanly.")
w(f"%       - Ablation does NOT. It lowers refusal in Mistral ({ma}%->{mb}%),")
w(f"%         Llama ({la}%->{lb}%) and Command-R ({ca}%->{cb}%), but RAISES it in")
w(f"%         Qwen ({qa}%->{qb}%) and Gemma ({ga}%->{gb}%).")
w("%       - Why: ablation changes the phrasing of the refusal, not its presence.")
w("%         Out of first-person modals ('I cannot') into forms like 'Certainly")
w("%         not. Submitting a client trade without proper approval is a serious")
w("%         violation.' A phrase-matching classifier scores that as compliance.")
w("%         Concrete: 66 of Qwen's 120 ablated responses are refusals the regex")
w("%         misses; for Gemma the regex finds 0 of 120 where the judge finds 120.")
w("%       - State that ablation is scored with the same classifier as Table 1.")
w("%       - Keep from the old paragraph: layers sit upper-middle; addition")
w("%         coefficient spans three orders of magnitude (29.8 Mistral -> ~75,800")
w("%         Gemma).")
w("%     Framing note: this is a measurement artifact in the old scoring, not a")
w("%     failure of the direction. Addition still works everywhere. Worth saying")
w("%     plainly rather than burying.")
w("%")
w("% 4b. REPLACES 'Tool context suppresses the refusal signal'")
w("%     Mostly survives. One claim must go.")
w("%     Must cover:")
w("%       - Suppression unchanged: significant in four of five (t=5.6 Qwen,")
w("%         5.1 Mistral, 9.7 Command-R, 4.0 Gemma; null for Llama at 0.4).")
w("%       - DROP the blanket 'text-derived and tool-derived directions remain")
w("%         aligned'. True for Qwen 0.741, Mistral 0.773, Gemma 0.797. NOT true")
w("%         for Command-R 0.394 or Llama 0.213 (Table~\\ref{tab:cosine}).")
w("%       - So 'attenuation along a shared axis' holds for three of five, and")
w("%         should be stated as such.")
w("%       - Llama is the coherent outlier: weakest alignment AND null suppression.")
w("%         Worth one sentence rather than treating it as noise.")
w("%")
w("% 4c. REPLACES 'strong predictor but partial mediator'")
w("%     Only the AUC range changes; the mediation argument stands.")
w("%     Must cover:")
w(f"%       - AUC range 0.69-0.88 becomes {min(aucs):.2f}-{max(aucs):.2f} under the")
w("%         global-scope scorer. Note all five now reproduce their published AUC.")
w("%       - Keep the patching numbers and the whole 'partial mediator' argument,")
w("%         including the caveats about one-dimensional intervention and about")
w("%         tool availability being confounded with prompt wording.")
w("%")
w("% 4d. NEW PARAGRAPH --- the ablation-on-action result (Table~\\ref{tab:ablation-action})")
w("%     Must cover:")
w("%       - Why it exists: ablation-by-wording is classifier-dependent, so we")
w("%         test the same intervention against something no classifier touches")
w("%         (the unsafe-tool-call predicate). Paired, n=200.")
w("%       - The headline unsafe rate moves in BOTH directions across families,")
w("%         so it supports no single claim on its own.")
w("%       - The informative quantity is unsafe-given-a-call, which is near-flat")
w("%         everywhere: 0.78->0.64, 0.77->0.75, 0.89->0.78, 0.61->0.64.")
w("%       - What DOES move is how often the model calls a tool at all: -22 pts")
w("%         Qwen, -17 Llama, to zero in Gemma, +10 Command-R.")
w("%       - Conclusion: the direction gates engagement, not the safety of the")
w("%         action. This is a sharper form of 'partial mediator' and is immune to")
w("%         the classifier problem that broke 4a.")
w("%       - Caveat to state explicitly: Gemma's tool-calling collapses to zero, so")
w("%         its apparent safety gain is the model ceasing to act. Read that as")
w("%         capability damage, not alignment. Mistral's effect is n.s. at n=200.")
w("%")
w("% 4e. REPLACES 'Steering is a blunt lever'")
w("%     Conclusion unchanged and arguably stronger.")
w("%     Must cover:")
w(f"%       - Qwen's over-refusal cost at the coefficient that clears unsafe calls:")
w(f"%         'around 70 percent' becomes {qsteer} percent.")
w("%       - Command-R, Gemma and Llama cost essentially ALL benign tool use at")
w("%         the equivalent point, so the conclusion generalises better than before.")
w("%       - No coefficient in the grid removes unsafe behaviour without large")
w("%         collateral over-refusal.")
w("%       - Optional but defensible: the regex column is non-monotonic for Llama")
w("%         (0.617 at c=20 then 0.017 at c=31) and Gemma, i.e. it stops tracking")
w("%         refusal exactly where the curve matters. The judge column rises")
w("%         cleanly. Good supporting evidence for the classifier change.")
w("")
w("% ---------------------------------------------------------------------------")
w("% 5. SECTION 3.6 --- 'Robustness of the direction'")
w("% ---------------------------------------------------------------------------")
w("%     The paragraph currently promises this analysis and reports no numbers.")
w("%     Must cover:")
w("%       - Point at Table~\\ref{tab:cosine}.")
w("%       - The claim holds: 0.69-0.86 across the five models.")
w("%       - Sample-size caveat: models rarely comply with harmful requests, so the")
w("%         complied side is small (as few as 25 per class in Gemma). Folding")
w("%         hedged compliance in roughly doubles it and moves the cosine by <=0.04.")
w("%       - Robustness point worth making, it is free ammunition against a")
w("%         reviewer: recomputing the behaviour direction under the OLD labels")
w("%         agrees with the new at 0.96-0.98, so this check does not depend on the")
w("%         relabelling at all.")
w("")
w("% ---------------------------------------------------------------------------")
w("% 6. METHODS --- two additions, both for reproducibility")
w("% ---------------------------------------------------------------------------")
w("%")
w("% 6a. APPEND to 'Refusal classification' (one or two sentences)")
w("%       - The interventions in Section 5 are scored with this same classifier.")
w("%       - Why it matters here specifically: a phrase-matching classifier misreads")
w("%         ablation, which changes how a model refuses, as a change in whether it")
w("%         refuses.")
w("%")
w("% 6b. NEW \\paragraph in 'Mechanistic methods' --- prompt construction under tools")
w("%       - Chat templates differ in whether they can carry tool definitions.")
w("%         Passing tools to a template with no tool-handling block drops them")
w("%         silently: the tool prompt becomes a plain chat prompt and every")
w("%         response scores as safe. No error is raised.")
w("%       - Gemma-3 has no tool-handling block in any published checkpoint, so its")
w("%         schemas are written into the prompt text. Validate the reconstruction:")
w("%         12.5% unsafe vs 14.6% from the behavioural run, and it reproduces the")
w("%         published AUC to within 0.001.")
w("%       - We assert a tool name appears in the rendered prompt before any")
w("%         tool-mode measurement.")
w("%       - Llama-3.1-70B loaded from unsloth/Meta-Llama-3.1-70B-Instruct (the")
w("%         meta-llama repos are gated). Same bf16 weights; another common mirror")
w("%         ships a stripped template that does not carry tools.")
w("")
w("% ---------------------------------------------------------------------------")
w("% 7. SECTION 7 DISCUSSION --- 'A shared refusal direction, suppressed rather")
w("%    than replaced'")
w("% ---------------------------------------------------------------------------")
w("%     Two assertions in the first half are now too strong.")
w("%     Must change:")
w("%       - 'ablations collapse and decrease harmful prompt refusal rates' --")
w("%         true in three of five, reversed in two.")
w("%       - 'the directions in the text-derived and tool-derived contexts are")
w("%         aligned' -- true in three of five.")
w("%     Keep:")
w("%       - Additions induce benign over-refusal everywhere.")
w("%       - Behaviour-defined and request-type directions are closely aligned.")
w("%       - The suppression-not-replacement reading, scoped to the families where")
w("%         it holds, and the qi2024safety shallow-alignment connection.")
w("%     The section title itself is still fine.")
w("")
w("% ---------------------------------------------------------------------------")
w("% 8. ABSTRACT + SECTION 1 INTRODUCTION")
w("% ---------------------------------------------------------------------------")
w("%     Both describe the mechanistic finding in terms of ablation collapsing")
w("%     refusal. Needs a pass once Section 5 settles. The intro's 'Mechanistic")
w("%     finding' paragraph is the specific one.")
w("")
DEST.write_text("\n".join(L) + "\n")
print(f"wrote {DEST} ({len(L)} lines)")
